### PR TITLE
hitbtc-js: fetchOrders

### PR DESCRIPTION
**Pull request by allbinmani**
Implemented fetchOrders, fetchOpenOrders and fetchClosedOrders for HitBTC.

### CODE REVIEW

**Comment by kroitor** [comment]
Yay! Merging this! Thank you a lot! )

**Comment by allbinmani** [comment]
Not sure if something I did causes Travis to fail, please advise.

**Comment by kroitor** [comment]
Well, as you may know, we support three languages. PHP and Python versions are generated from the JS source. So, to make the JS code portable it has to be written in a "special flavour", described in our [CONTRIBUTING](https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md) doc. Our build process is also covered there (though, it maybe somewhat outdated).

You can take a look at why it crashed, here's the log: https://travis-ci.org/ccxt-dev/ccxt/builds/286171265

Travis complains, because after converting the JS to Python, it turned out to be syntactically incorrect in Python:

screen shot 2017-10-10 at 22 07 18

Our transpiler is not as smart and works line-by-line )) 

In order to keep the code transpileable, we devised the following set of portability rules: https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

But don't worry, I'll merge it properly anyway. Just make sure to read the CONTRIBUTING doc before your next PR ) Your help is welcome! Thx!

**Comment by allbinmani** [comment]
I _did_ read the CONTRIBUTING doc, but still failed to follow code style 🤓  🌴  
Well well, at least I added my changes in the right place. .

**Comment by kroitor** [comment]
@allbinmani don't worry, it's ok ) It's not easy to follow those rules entirely at first ) The code is a very unusual mix of JS + Python + PHP + C style ) Basically we use their common subset. I'm already merging it anyway, all fine )

**Comment by kroitor** [comment]
I'll upload a merged version and you can then compare it to your version to see the difference. Will be there soon )

**Comment by kroitor** [comment]
Can't find fetchOrders, but I guess, I'll just do fetchOpenOrders / fetchClosedOrders for now )

**Comment by kroitor** [comment]
Ok, I merged it, but didn't have time to test it thoroughly yet. Please update to version 1.9.98+ in approx 5 minutes and check if everything works normally for you.

**Comment by kroitor** [comment]
Reference [Unified order API #71](https://github.com/ccxt-dev/ccxt/issues/71).

**Comment by kroitor** [comment]
Looks like HitBTC v1 /api/1/trading/orders/recent endpoint always return an empty list of orders. At least for me. No error, normal reply, but the order array is `[ nothing here ]`. I guess we will have to emulate fetchClosedOrders with their private trades API (it seems to be working) + fetchMyTrades method.

**Pull request merged**
