### PR TITLE
Add bitfinex price_precision

### PR DESCRIPTION
**Pull request by aking7**
#371: Added `precision['price']` to `fetchMarkets()` for `bitfinex` class.

I'm unable to build it locally as discussed, but hopefully it works on your end.

### CODE REVIEW

**Comment by kroitor** [comment]
@aking7 thx! I'll keep you updated on our progress of fixing the windows build! But this PR should really work seamlessly anyway.

**Comment by kroitor** [comment]
Merged it ;) It does work, thx a lot!

**Comment by aking7** [comment]
@kroitor Great! It wasn't much but hopefully I can add some more in the future ;)

**Comment by kroitor** [comment]
@aking7 you're welcome!

**Pull request merged**
