### PR TITLE
cex.io: added 'fetchOpenOrders()'

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by mkutny** [comment]
Not sure I understand this build process completely.

So I updated `ccxt.js` and it works for me. It seems there is an issue with a transpiler or I'm supposed to build it in some unusual way?

**Comment by kroitor** [comment]
@mkutny hi! Thx for the pull request! I'm merging it! )

As for your question, the transpilation process and the rules are here: https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

```
    parseOrder(order) { // ← space before ( missed
      return {
        'id':        order.id,        // ← extra spaces violate PEP8
        'datetime':  this.iso8601(parseInt(order.time)), // ← dot access instead of key access, no spaces
        'timestamp': order.time,      // ← dot access instead of key access,
        'status':    'open',          
        'symbol':    order.symbol1 + '/' + order.symbol2,    
        'type':      undefined,       
        'side':      order.type,      
        'price':     order.price,     
        'amount':    order.amount,    
        'filled':    order.amount - order.pending,          
        'remaining': order.pending,   
        'trades':    undefined,       
        'fee':       undefined,
        'info':      order,           
      }
    },

    async fetchOpenOrders(symbol = undefined, params = {}) { // space missed before (
      if (!symbol)
          throw new ExchangeError (this.id + ' requires a symbol');
                                                                               // ← an empty line inside the derived method
      await this.loadMarkets();
      const orders = await this.privatePostOpenOrders(symbol); // ← this method accepts a dictionary
      return this.parseOrders(orders);
                                                                               // ← another empty line
    },
```

Basically, the general rule is that the transpiler works with regexps line by line and the spacing is critical for PEP8 and for several special cases. But don't worry, I'll merge it anyway. Thx a lot!

**Comment by kroitor** [comment]
Ok, it has arrived in v.1.9.73+! )
Let us know if you have any difficulty with it. Thx for your help, it is very welcome and it really means a lot to us!
Cheers!

**Comment by kroitor** [comment]
@mkutny looks like it's there ) Please update to 1.9.75+ before trying it. Best wishes.

**Comment by mkutny** [comment]
Now it works like a charm, great!

**Comment by kroitor** [comment]
good-news

**Pull request merged**
