### PR TITLE
Made camel case definitions more pythonic ...

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by kroitor** [comment]
Hi, @frosty00 ! Thx for your help! We'll merge it ) Travis is [complaining](https://travis-ci.org/ccxt-dev/ccxt/builds/288609445) at line 671 (we have PEP8 validation with flake8 there), can you remove the excessive empty line to let the tests pass, please? Thx in advance! ) We really appreciate your involvement!

**Comment by xpl** [comment]
This is incredibly useful fix. Thank you a lot. BTW, I think the productivity of a programmer should be measured in code deletions instead of additions! :)

screen shot 2017-10-16 at 18 51 44

**Comment by frosty00** [comment]
Removed the blank line. Thanks @xpl this is actually the first time I have found a good use of setattr after having recently learned how it works. First of many commits hopefully (;

**Comment by frosty00** [comment]
Also does the change remain once the python file is transpiled from javascript or will it be overwritten?

**Comment by xpl** [comment]
@frosty00 That file (`exchange.py`) is not transpiled, as it contains the Python-specific part of the codebase. The one that _is_ transpiled is `exchanges.py`.

In future, this `camelCase` vs `under_score` duality will be resolved in compile time instead of doing it dynamically. This means that we will substitute function names when doing transpilation. So Python people will get under_scores and JavaScript will get camelCase, and everyone's happy.

**Comment by kroitor** [comment]
@frosty00, awesome! Thx again for your participation! We'll be looking forward for more PRs from you! ) Cheers!

**Comment by kroitor** [comment]
This is what I was afraid of... https://github.com/ccxt-dev/ccxt/issues/331

**Comment by xpl** [comment]
@kroitor This is not the guy's fault, as we had our Python2 tests mistakenly skipped from the CI build, thus rendering us unable to catch the error early.

**Comment by kroitor** [comment]
@xpl yep, I know, fixed it already, no worries )

**Pull request merged**
