### PR TITLE
limits, fees, precision added to kuna

### PR DESCRIPTION
**Pull request by mkutny**

### CODE REVIEW

**Comment by kroitor** [comment]
Awesome! Merging it now! One question, though: are you sure that price precision is 0 (decimal digits) ? It kinda forces all prices to integer types...

**Comment by mkutny** [comment]
Price precision is `0` (so no digits after `.`).
Technically fractions of UAH are accepted but then exchange simply truncates them to integers.

When you say "types" in "forcing all prices to integer types" - you don't mean type coercion, right?

**Comment by kroitor** [comment]
@mkutny , no I mean formatting the float to precision. If 0 is their actual setting, we're all fine! Thx!

**Comment by kroitor** [comment]
I was mostly worried of KUN/BTC and BCH/BTC, because:

screen shot 2017-10-18 at 11 04 06

**Comment by kroitor** [comment]
So it looks like we need to define precision per market (just as you did with limits)...

**Comment by mkutny** [comment]
Hmm, you're right.

Since it's not in their API it needed some experiments so I left limits for `BTC` quotes for later (as I don't have BTC there).

I'd define `precision` in a per-market manner but at the same time, this would require us to provide unified API to provide `precisions` to clients.

Something like `getPrecision(market)` what do you think?

**Comment by kroitor** [comment]
@mkutny as for the interface we already have:
- `.feeToPrecision (...)`
- `.amountToPrecision (...)`
- `.costToPrecision (...)`

And regarding the accessor, do you really think we need one? Why not accessing it as usual?

```Python
# pythonic style
exchange.markets['BCH/BTC']['precision']['price']
exchange.markets['BCH/BTC']['precision']['amount']
exchange.markets['BCH/BTC']['precision']['cost']  #  this is not always present 
```

```JavaScript
# js style
exchange.markets['BCH/BTC'].precision.price
exchange.markets['BCH/BTC'].precision.amount
exchange.markets['BCH/BTC'].precision.cost  //  this is not always present 
```

To me, the above looks like an easy and understandable interface... So, to each market we simply need to add the following (the same thing is done in several exchanges already where markets are fetched online).

```
'markets': {
    ...
                                                       ↓ this and this ↓
    'BCH/BTC': { 'id': 'bchbtc', ... 'precision': { 'price': 8, 'amount': XXX }, 'limits': { ...
    ...
},
```

**Comment by kroitor** [comment]
Or did i misunderstand your question?

**Comment by mkutny** [comment]
You've got my question right. I was more concerned about making access to `precision` unified, if it's a property rather than a function then it's perfectly ok.

**Comment by kroitor** [comment]
@mkutny most of the problems that arise are due to the fact, that precision and fee calculation formulas are exchange-specific and are not documented at all. This info is actually very important to algorithmic traders and very few exchanges have it defined formally... Most of the time we have to reverse-engineer it by placing orders of different sizes and that itself requires having positive balances everywhere...

**Pull request merged**
